### ISSUE TITLE
Any plan to update 5.5 ?

### ISSUE THREAD

**Issue by themaluxis** [helfrichmichael/cura-novnc#15]
Hello there, 5.5 is out with many features
Do you plan to update docker to it ? thanks a lot

**Comment by Ernold11** [comment]
I created a fork with a fix for downloading the newest versions:
https://github.com/Ernold11/cura-novnc
Feel free to use it until the author does not change it in his repository.

**Comment by helfrichmichael** [comment]
Apologies for the delay here. With the frequent naming changes, etc it's been a challenge to keep this autoreleasing and happy. I'll take a look to see if I can get this running again.

Thanks for sharing yours in the meantime, @Ernold11 and sorry again for the delay here!

**Comment by helfrichmichael** [comment]
Fixed in https://github.com/helfrichmichael/cura-novnc/commit/0dbc23a6ec4cac190be857ce245ead7b52f1dcde.

Thanks again for the patience, all it took apparently was `-X64` appended to the name.

**Comment by helfrichmichael** [comment]
Image just pushed to DockerHub!
