### ISSUE TITLE
No "open file" dialogue

### ISSUE THREAD

**Issue by RealCommerzpunk** [helfrichmichael/cura-novnc#4]
Good day,
after updating the container to and having Cura 5 inside, there is an issue with openin files.
When I click "open" no windows opens to choose a file.
The only workarrond I found is, to rename my .stl files to one from the "recent" list, it will open then from picking it there.

Would you please investigate?

**Comment by helfrichmichael** [comment]
Hi @RealCommerzpunk ,

This is likely due to https://github.com/Ultimaker/Cura/issues/12266. I tried a few things locally to no avail so we might have to follow along on the upstream bug.

**Comment by RealCommerzpunk** [comment]
Thank you for investigating! I now just hope for a quick solution by cura, because I cant use the common workarrond "drag and drop into cura" because its a docker, lol. ;)

**Comment by helfrichmichael** [comment]
That's no problem, actually!

Reduce the window size of Cura in the docker or minimize temporarily. Then you can right click the desktop and click "File Explorer" visiting /prints should take you to your GCODE and STLs.

Example screenshot
![image](https://user-images.githubusercontent.com/9116898/173582007-7ca4bd0d-87ac-4e4e-9569-160bfaaab69e.png)

**Comment by Tamperold** [comment]
Thanks first of all for the Docker image.
But is there also another solution for exporting the G-code?
Opening is quite simple via drag and drop.
Thanks!

**Comment by Ernold11** [comment]
Hi, could you try this WO:
```
sudo apt-get install xdg-desktop-portal-gtk
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
```
It should fix the problem of not showing the open file window.

**Comment by RealCommerzpunk** [comment]
I tried, but i cant run the commands. I tried 2 ways: The "console" window from the unraid docker menu and second, the "terminal" window in the running GUI. Both result with "sudo: not found".

Then I tried the command without "sudo".
Inside the GUI it results with "E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?"
From unraid "E: Unable to locate package xdg-desktop-portal-gtk"

So I cant help, what am I missing?

**Comment by Ernold11** [comment]
@RealCommerzpunk

On host:
`sudo docker exec -it --user root <CONTAINER_NAME> /bin/bash`

Then in container:
```
apt-get update
apt-get install xdg-desktop-portal-gtk dbus-x11 -y
service dbus start
export $(dbus-launch)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
```
Next open web browser, right click -> select terminal and paste:
```
export $(dbus-launch)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORIT
```
And everything should working.
![cura](https://user-images.githubusercontent.com/41105075/192165296-578b553d-a7c5-470e-9af2-34ae77defc55.jpg)

@helfrichmichael 
Do you think about adding this WO to your Dockerfile? It should resolve the problem until cura resolves it on their site.

**Comment by Ernold11** [comment]
@helfrichmichael 
I have problem when I try to build container using your Dockerfile:
```
Step 10/17 : RUN chmod +x /cura/get_latest_cura_release.sh   && latestCura=$(/cura/get_latest_cura_release.sh url)   && curaReleaseName=$(/cura/get_latest_cura_release.sh name)   && curl -sSL ${latestCura} > ${curaReleaseName}   && rm -f /cura/releaseInfo.json   && chmod +x /cura/${curaReleaseName}   && /cura/${curaReleaseName} --appimage-extract   && rm /cura/${curaReleaseName}   && rm -rf /var/lib/apt/lists/*   && apt-get autoclean   && groupadd cura   && useradd -g cura --create-home --home-dir /home/cura cura   && mkdir -p /cura   && mkdir -p /prints/   && chown -R cura:cura /cura/ /home/cura/ /prints/   && mkdir -p /home/cura/.config/   && echo "XDG_DOWNLOAD_DIR=\"/prints/\"" >> /home/cura/.config/user-dirs.dirs   && echo "file:///prints prints" >> /home/cura/.gtk-bookmarks
 ---> Running in a286c6276375
chmod: cannot access '/cura/Ultimaker-Cura-5.1.1-linux-modern.AppImage': No such file or directory
chmod: cannot access 'Ultimaker-Cura-5.1.1-linux.AppImage': No such file or directory
The command '/bin/sh -c chmod +x /cura/get_latest_cura_release.sh   && latestCura=$(/cura/get_latest_cura_release.sh url)   && curaReleaseName=$(/cura/get_latest_cura_release.sh name)   && curl -sSL ${latestCura} > ${curaReleaseName}   && rm -f /cura/releaseInfo.json   && chmod +x /cura/${curaReleaseName}   && /cura/${curaReleaseName} --appimage-extract   && rm /cura/${curaReleaseName}   && rm -rf /var/lib/apt/lists/*   && apt-get autoclean   && groupadd cura   && useradd -g cura --create-home --home-dir /home/cura cura   && mkdir -p /cura   && mkdir -p /prints/   && chown -R cura:cura /cura/ /home/cura/ /prints/   && mkdir -p /home/cura/.config/   && echo "XDG_DOWNLOAD_DIR=\"/prints/\"" >> /home/cura/.config/user-dirs.dirs   && echo "file:///prints prints" >> /home/cura/.gtk-bookmarks' returned a non-zero code: 1
```
Could you help with resolve that?

**Comment by Ernold11** [comment]
Unfortunately on the new container with Cura 5.1.1 fix is not working.

@update
It is more complicated now. You need to do all that steps above but then run cura using command:
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 /bin/sh -c /cura/squashfs-root/AppRun`

I cannot find but in one of the open issue on cura was information to use:
`Ultimaker-Cura-5.1.1-linux-modern.AppImage`
for updated linux distros instead of normal version:
`Ultimaker-Cura-5.1.1-linux.AppImage`
That version should work.

**Comment by helfrichmichael** [comment]
Thanks to https://github.com/Ultimaker/Cura/issues/12266#issuecomment-1274861668 I think we have a viable fix. Testing now and if all is good, I'll push shortly.

**Comment by helfrichmichael** [comment]
Thanks for the patience! 

https://github.com/helfrichmichael/cura-novnc/actions/runs/3238503566 is rolling out with the fix now. I'll mark this as resolved.
