### ISSUE TITLE
VNC direct connect

### ISSUE THREAD

**Issue by jonathanm-ur** [helfrichmichael/cura-novnc#5]
Can we open a port into the container and directly access with a VNC client in addition to the browser noVNC implementation?

**Comment by helfrichmichael** [comment]
Ack. Taking a look at this now.

**Comment by helfrichmichael** [comment]
This was done in https://github.com/helfrichmichael/cura-novnc/commit/40d47de4149c49de29466a9b211263f40f13c2a8. Let me know if you have issues with accessing that.
